const $=id=>document.getElementById(id);
async function api(path,options={}){const r=await fetch(path,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});let d=null;try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d?.message||"Não foi possível concluir a operação.");e.status=r.status;throw e}return d}
let products=[],orders=[],editingProduct=null;
document.addEventListener("DOMContentLoaded",init);
async function init(){$("loginForm").addEventListener("submit",login);$("logoutButton").addEventListener("click",logout);document.querySelectorAll(".nav-button").forEach(b=>b.onclick=()=>showSection(b.dataset.section));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>showSection(b.dataset.go));$("newProductButton").onclick=()=>openProduct();$("closeModal").onclick=closeProduct;$("cancelProduct").onclick=closeProduct;$("addVariant").onclick=()=>addVariant();$("productForm").onsubmit=saveProduct;$("productSearch").oninput=renderProducts;$("refreshOrders").onclick=loadOrders;$("refreshStock").onclick=loadStockMovements;try{const s=await api("/api/admin/session");await enterApp(s)}catch{showLogin()}}
function showLogin(){$("loginView").classList.remove("hidden");$("appView").classList.add("hidden");$("loginEmail").focus()}
async function login(e){e.preventDefault();$("loginError").textContent="";try{await enterApp(await api("/api/admin/login",{method:"POST",body:JSON.stringify({email:$("loginEmail").value.trim(),password:$("loginPassword").value})}))}catch(e){$("loginError").textContent=e.message}}
async function logout(){try{await api("/api/admin/logout",{method:"POST"})}catch{}products=[];orders=[];showLogin();$("loginPassword").value=""}
async function enterApp(s){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("adminEmail").textContent=s.email||"Administrador";try{await Promise.all([loadProducts(),loadOrders(),loadStockMovements()]);renderDashboard()}catch(e){showLogin();$("loginError").textContent=e.message}}
function showSection(s){document.querySelectorAll(".section").forEach(x=>x.classList.add("hidden"));$(s+"Section").classList.remove("hidden");document.querySelectorAll(".nav-button").forEach(b=>b.classList.toggle("active",b.dataset.section===s));$("pageTitle").textContent={dashboard:"Visão geral",products:"Produtos",orders:"Pedidos",stock:"Estoque"}[s];if(s==="products")renderProducts();if(s==="orders")renderOrders();if(s==="stock")renderStock()}
async function loadProducts(){const d=await api("/api/admin/products");products=d.products||[];renderProducts();renderStock();renderDashboard()}
async function loadStockMovements(){try{const d=await api("/api/admin/stock/movements");renderStockMovements(d.movements||[])}catch(e){$("stockMovements").innerHTML='<p>'+esc(e.message)+'</p>'}}
async function loadOrders(){const d=await api("/api/admin/orders");orders=d.orders||[];renderOrders();renderDashboard()}
function renderDashboard(){$("statProducts").textContent=products.filter(p=>p.active).length;$("statOrders").textContent=orders.length;$("statPaid").textContent=orders.filter(o=>["paid","processing","shipped","delivered"].includes(o.status)).length;$("statLowStock").textContent=products.reduce((n,p)=>n+(p.product_variants||[]).filter(v=>v.stock<=2&&v.active).length,0);$("recentOrders").innerHTML=orderTable(orders.slice(0,5))}
function renderProducts(){const q=($("productSearch").value||"").toLowerCase();const list=products.filter(p=>(p.name+" "+(p.sku||"")).toLowerCase().includes(q));$("productsGrid").innerHTML=list.map(p=>{const img=Array.isArray(p.images)&&p.images[0]?p.images[0]:"";const stock=(p.product_variants||[]).reduce((n,v)=>n+Number(v.stock||0),0);return `<article class="admin-product"><img src="${esc(img)}" onerror="this.style.visibility='hidden'"><div class="admin-product-body"><h3>${esc(p.name)}</h3><div class="meta">${esc(p.sku||"SEM SKU")} · ${money(p.sale_price||p.price)} · estoque ${stock}</div><div class="admin-product-actions"><button onclick="openProduct('${p.id}')">EDITAR</button><button class="secondary" onclick="toggleProduct('${p.id}',${!p.active})">${p.active?"DESATIVAR":"ATIVAR"}</button></div></div></article>`}).join("")||"<p>Nenhum produto encontrado.</p>"}
function renderStock(){const rows=[];products.forEach(p=>(p.product_variants||[]).forEach(v=>rows.push([p,v])));$("stockTable").innerHTML=`<table class="table"><thead><tr><th>PRODUTO</th><th>COR</th><th>SKU</th><th>ESTOQUE</th><th>STATUS</th><th></th></tr></thead><tbody>${rows.map(([p,v])=>`<tr><td>${esc(p.name)}</td><td>${esc(v.color)}</td><td>${esc(v.sku||p.sku||"")}</td><td class="${v.stock<=2?"stock-low":""}">${v.stock}</td><td>${v.active?"Ativo":"Inativo"}</td><td><button class="secondary small-button" onclick="adjustStock('${v.id}','${esc(p.name+" — "+v.color)}',${Number(v.stock||0)})">AJUSTAR</button></td></tr>`).join("")||"<tr><td colspan='6'>Nenhuma variação cadastrada.</td></tr>"}</tbody></table>`}
function renderStockMovements(list){if(!list.length){$("stockMovements").innerHTML="<p>Nenhuma movimentação registrada.</p>";return}$("stockMovements").innerHTML=`<table class="table"><thead><tr><th>DATA</th><th>PRODUTO</th><th>COR</th><th>TIPO</th><th>QTD.</th><th>MOTIVO</th><th>POR</th></tr></thead><tbody>${list.map(m=>{const v=m.product_variants||{},p=v.products||{};return `<tr><td>${date(m.created_at)}</td><td>${esc(p.name||"—")}</td><td>${esc(v.color||"—")}</td><td>${esc(m.movement_type||"—")}</td><td class="${Number(m.quantity_delta)<0?"stock-negative":"stock-positive"}">${Number(m.quantity_delta)>0?"+":""}${m.quantity_delta}</td><td>${esc(m.reason||"—")}</td><td>${esc(m.created_by||"—")}</td></tr>`}).join("")}</tbody></table>`}

async function adjustStock(variantId,label,current){const raw=window.prompt(`Ajuste de estoque para ${label}.\nEstoque atual: ${current}\nInforme a quantidade a alterar (ex.: +5 ou -2):`);if(raw===null)return;const delta=Number(String(raw).replace(",","."));if(!Number.isInteger(delta)||delta===0){window.alert("Informe um número inteiro diferente de zero.");return}const reason=window.prompt("Motivo do ajuste:","Reposição de estoque");if(reason===null)return;try{await api("/api/admin/stock/adjust",{method:"POST",body:JSON.stringify({variant_id:variantId,delta,movement_type:delta>0?"restock":"adjustment",reason})});await Promise.all([loadProducts(),loadStockMovements()]);}catch(e){window.alert(e.message)}}

function orderTable(list){if(!list.length)return "<p>Nenhum pedido encontrado.</p>";return `<table class="table order-table"><thead><tr><th>PEDIDO</th><th>CLIENTE</th><th>DATA</th><th>TOTAL</th><th>STATUS</th><th></th></tr></thead><tbody>${list.map(o=>`<tr><td><button class="link-button" onclick="openOrder('${o.id}')">${esc(o.order_nsu||"—")}</button></td><td>${esc(o.customer_name||"—")}</td><td>${date(o.created_at)}</td><td>${money(o.total)}</td><td><span class="badge ${esc(o.status||"pending")}">${statusLabel(o.status)}</span></td><td><button class="secondary small-button" onclick="openOrder('${o.id}')">DETALHES</button></td></tr>`).join("")}</tbody></table>`}
function renderOrders(){$("ordersTable").innerHTML=orderTable(orders)}
function statusLabel(s){return({pending:"Aguardando pagamento",paid:"PAGO",processing:"SEPARANDO",shipped:"ENVIADO",delivered:"ENTREGUE"})[s]||s||"—"}
function openOrder(id){const o=orders.find(x=>String(x.id)===String(id));if(!o)return;$("orderModalTitle").textContent=o.order_nsu||"Pedido";$("orderDetails").innerHTML=orderDetail(o);$("orderModal").classList.remove("hidden")}
function closeOrder(){$("orderModal").classList.add("hidden")}
function orderDetail(o){const a=o.customer_address||{},p=(o.payments||[])[0]||{},items=o.order_items||[];const address=[a.street&&a.number?`${a.street}, ${a.number}`:a.street||"",a.complement||"",a.neighborhood||"",a.cep||"",a.city&&a.state?`${a.city} - ${a.state}`:a.city||a.state||""].filter(Boolean).join(" · ");return `<div class="order-summary-grid"><div class="detail-card"><h3>Cliente</h3><p><strong>${esc(o.customer_name||"—")}</strong></p><p>${esc(o.customer_email||"—")}</p><p>${esc(o.customer_phone||"—")}</p><p>CPF: ${esc(o.customer_cpf||"—")}</p></div><div class="detail-card"><h3>Entrega</h3><p>${esc(address||"—")}</p><p>Frete: ${money(o.shipping)}</p></div><div class="detail-card"><h3>Pagamento</h3><p>Status: <strong>${esc(statusLabel(o.status))}</strong></p><p>Transação: ${esc(o.transaction_nsu||p.transaction_nsu||"—")}</p><p>Parcelas: ${esc(o.installments||p.installments||"—")}</p><p>Pago em: ${date(o.paid_at||p.created_at)}</p>${o.receipt_url||p.receipt_url?`<a href="${esc(o.receipt_url||p.receipt_url)}" target="_blank" rel="noopener">Abrir comprovante</a>`:""}</div><div class="detail-card"><h3>Resumo</h3><p>Subtotal: ${money(o.subtotal)}</p><p>Frete: ${money(o.shipping)}</p><p class="total-line">Total: ${money(o.total)}</p></div></div><div class="detail-card"><h3>Produtos</h3><div class="order-items">${items.length?items.map(i=>`<div class="order-item"><div><strong>${esc(i.product_name)}</strong><span>${esc(i.variant_color||"Sem cor")} · SKU ${esc(i.sku||"—")}</span></div><div>${i.quantity} × ${money(i.unit_price)}<br><strong>${money(i.total_price)}</strong></div></div>`).join(""):"<p>Nenhum item registrado.</p>"}</div></div><div class="detail-card"><h3>Expedição</h3><div class="status-actions"><label>Status<select id="orderStatus">${["paid","processing","shipped","delivered"].map(s=>`<option value="${s}" ${o.status===s?"selected":""}>${statusLabel(s)}</option>`).join("")}</select></label><label>Transportadora<input id="shippingCarrier" value="${esc(o.shipping_carrier||"")}" placeholder="Ex.: Correios"></label><label>Código de rastreio<input id="trackingCode" value="${esc(o.tracking_code||"")}" placeholder="Código"></label><label>Link de rastreio<input id="trackingUrl" value="${esc(o.tracking_url||"")}" placeholder="https://..."></label></div><div id="orderUpdateError" class="error"></div><div class="modal-actions"><button class="secondary" onclick="closeOrder()">FECHAR</button><button onclick="saveOrderStatus('${o.id}')">SALVAR STATUS</button></div></div>`}
async function saveOrderStatus(id){const status=$("orderStatus").value;const body={status,shipping_carrier:$("shippingCarrier").value.trim(),tracking_code:$("trackingCode").value.trim(),tracking_url:$("trackingUrl").value.trim()};$("orderUpdateError").textContent="";if(status==="shipped"&&!body.tracking_code){$("orderUpdateError").textContent="Informe o código de rastreio para marcar como enviado.";return}try{await api(`/api/admin/orders/${encodeURIComponent(id)}/status`,{method:"PATCH",body:JSON.stringify(body)});await loadOrders();openOrder(id)}catch(e){$("orderUpdateError").textContent=e.message}}

function openProduct(id=null){editingProduct=id?products.find(p=>p.id===id):null;$("modalTitle").textContent=editingProduct?"Editar produto":"Novo produto";$("productId").value=editingProduct?.id||"";$("productName").value=editingProduct?.name||"";$("productSku").value=editingProduct?.sku||"";$("productCategory").value=editingProduct?.category||"bolsas";$("productPrice").value=editingProduct?.price??"";$("productSalePrice").value=editingProduct?.sale_price??"";$("productShippingWeight").value=editingProduct?.shipping_weight_kg??"";$("productShippingHeight").value=editingProduct?.shipping_height_cm??"";$("productShippingWidth").value=editingProduct?.shipping_width_cm??"";$("productShippingLength").value=editingProduct?.shipping_length_cm??"";$("productImages").value=Array.isArray(editingProduct?.images)?editingProduct.images.join("\n"):"";$("productDescription").value=editingProduct?.description||"";$("productNew").checked=!!editingProduct?.is_new;$("productSale").checked=!!editingProduct?.is_sale;$("productActive").checked=editingProduct?!!editingProduct.active:true;$("formError").textContent="";$("variantsList").innerHTML="";(editingProduct?.product_variants||[]).forEach(v=>addVariant(v));$("productModal").classList.remove("hidden")}
function closeProduct(){$("productModal").classList.add("hidden");editingProduct=null}
function addVariant(v={}){const row=document.createElement("div");row.className="variant-row";row.dataset.id=v.id||"";row.innerHTML=`<input class="v-color" placeholder="Cor" value="${esc(v.color||"")}"><input class="v-sku" placeholder="SKU da cor" value="${esc(v.sku||"")}"><input class="v-stock" type="number" min="0" value="${Number(v.stock||0)}"><button type="button" class="remove-variant">×</button>`;row.querySelector(".remove-variant").onclick=()=>row.remove();$("variantsList").appendChild(row)}
async function saveProduct(e){e.preventDefault();$("formError").textContent="";const id=$("productId").value;const payload={name:$("productName").value.trim(),sku:$("productSku").value.trim()||null,category:$("productCategory").value,price:Number($("productPrice").value),sale_price:$("productSalePrice").value?Number($("productSalePrice").value):null,description:$("productDescription").value.trim(),images:$("productImages").value.split(/\\r?\\n/).map(x=>x.trim()).filter(Boolean),shipping_weight_kg:$("productShippingWeight").value?Number($("productShippingWeight").value):null,shipping_height_cm:$("productShippingHeight").value?Number($("productShippingHeight").value):null,shipping_width_cm:$("productShippingWidth").value?Number($("productShippingWidth").value):null,shipping_length_cm:$("productShippingLength").value?Number($("productShippingLength").value):null,is_new:$("productNew").checked,is_sale:$("productSale").checked,active:$("productActive").checked};if(!payload.name){$("formError").textContent="Informe o nome.";return}try{const d=await api(id?`/api/admin/products/${encodeURIComponent(id)}`:"/api/admin/products",{method:id?"PUT":"POST",body:JSON.stringify(payload)});const pid=d.product.id;const variants=[...document.querySelectorAll(".variant-row")].map(r=>({id:r.dataset.id||null,color:r.querySelector(".v-color").value.trim(),sku:r.querySelector(".v-sku").value.trim()||null,stock:Math.max(0,Number(r.querySelector(".v-stock").value||0)),active:true})).filter(v=>v.color);await api(`/api/admin/products/${encodeURIComponent(pid)}/variants`,{method:"PUT",body:JSON.stringify({variants})});closeProduct();await loadProducts()}catch(e){$("formError").textContent=e.message}}
async function toggleProduct(id,active){const p=products.find(x=>x.id===id);if(!p)return;try{await api(`/api/admin/products/${encodeURIComponent(id)}`,{method:"PUT",body:JSON.stringify({name:p.name,sku:p.sku,category:p.category,price:p.price,sale_price:p.sale_price,description:p.description,images:Array.isArray(p.images)?p.images:[],images:p.images,is_new:p.is_new,is_sale:p.is_sale,active})});await loadProducts()}catch(e){alert(e.message)}}
function money(v){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0))}
function date(v){return v?new Date(v).toLocaleString("pt-BR"):"—"}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
