const $=id=>document.getElementById(id);
async function api(path,options={}){const r=await fetch(path,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});let d=null;try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d?.message||"Não foi possível concluir a operação.");e.status=r.status;throw e}return d}
let products=[],orders=[],editingProduct=null;
document.addEventListener("DOMContentLoaded",init);
async function init(){$("loginForm").addEventListener("submit",login);$("logoutButton").addEventListener("click",logout);document.querySelectorAll(".nav-button").forEach(b=>b.onclick=()=>showSection(b.dataset.section));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>showSection(b.dataset.go));$("newProductButton").onclick=()=>openProduct();$("closeModal").onclick=closeProduct;$("cancelProduct").onclick=closeProduct;$("addVariant").onclick=()=>addVariant();$("productForm").onsubmit=saveProduct;$("productSearch").oninput=renderProducts;$("refreshOrders").onclick=loadOrders;try{const s=await api("/api/admin/session");await enterApp(s)}catch{showLogin()}}
function showLogin(){$("loginView").classList.remove("hidden");$("appView").classList.add("hidden");$("loginEmail").focus()}
async function login(e){e.preventDefault();$("loginError").textContent="";try{await enterApp(await api("/api/admin/login",{method:"POST",body:JSON.stringify({email:$("loginEmail").value.trim(),password:$("loginPassword").value})}))}catch(e){$("loginError").textContent=e.message}}
async function logout(){try{await api("/api/admin/logout",{method:"POST"})}catch{}products=[];orders=[];showLogin();$("loginPassword").value=""}
async function enterApp(s){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("adminEmail").textContent=s.email||"Administrador";try{await Promise.all([loadProducts(),loadOrders()]);renderDashboard()}catch(e){showLogin();$("loginError").textContent=e.message}}
function showSection(s){document.querySelectorAll(".section").forEach(x=>x.classList.add("hidden"));$(s+"Section").classList.remove("hidden");document.querySelectorAll(".nav-button").forEach(b=>b.classList.toggle("active",b.dataset.section===s));$("pageTitle").textContent={dashboard:"Visão geral",products:"Produtos",orders:"Pedidos",stock:"Estoque"}[s];if(s==="products")renderProducts();if(s==="orders")renderOrders();if(s==="stock")renderStock()}
async function loadProducts(){const d=await api("/api/admin/products");products=d.products||[];renderProducts();renderStock();renderDashboard()}
async function loadOrders(){const d=await api("/api/admin/orders");orders=d.orders||[];renderOrders();renderDashboard()}
function renderDashboard(){$("statProducts").textContent=products.filter(p=>p.active).length;$("statOrders").textContent=orders.length;$("statPaid").textContent=orders.filter(o=>["paid","processing","shipped","delivered"].includes(o.status)).length;$("statLowStock").textContent=products.reduce((n,p)=>n+(p.product_variants||[]).filter(v=>v.stock<=2&&v.active).length,0);$("recentOrders").innerHTML=orderTable(orders.slice(0,5))}
function renderProducts(){const q=($("productSearch").value||"").toLowerCase();const list=products.filter(p=>(p.name+" "+(p.sku||"")).toLowerCase().includes(q));$("productsGrid").innerHTML=list.map(p=>{const img=Array.isArray(p.images)&&p.images[0]?p.images[0]:"";const stock=(p.product_variants||[]).reduce((n,v)=>n+Number(v.stock||0),0);return `<article class="admin-product"><img src="${esc(img)}" onerror="this.style.visibility='hidden'"><div class="admin-product-body"><h3>${esc(p.name)}</h3><div class="meta">${esc(p.sku||"SEM SKU")} · ${money(p.sale_price||p.price)} · estoque ${stock}</div><div class="admin-product-actions"><button onclick="openProduct('${p.id}')">EDITAR</button><button class="secondary" onclick="toggleProduct('${p.id}',${!p.active})">${p.active?"DESATIVAR":"ATIVAR"}</button></div></div></article>`}).join("")||"<p>Nenhum produto encontrado.</p>"}
function renderStock(){const rows=[];products.forEach(p=>(p.product_variants||[]).forEach(v=>rows.push([p.name,v.color,v.sku||p.sku||"",v.stock,v.active])));$("stockTable").innerHTML=`<table class="table"><thead><tr><th>PRODUTO</th><th>COR</th><th>SKU</th><th>ESTOQUE</th><th>STATUS</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r[0])}</td><td>${esc(r[1])}</td><td>${esc(r[2])}</td><td class="${r[3]<=2?"stock-low":""}">${r[3]}</td><td>${r[4]?"Ativo":"Inativo"}</td></tr>`).join("")||"<tr><td colspan='5'>Nenhuma variação cadastrada.</td></tr>"}</tbody></table>`}
function orderTable(list){if(!list.length)return "<p>Nenhum pedido encontrado.</p>";return `<table class="table"><thead><tr><th>PEDIDO</th><th>CLIENTE</th><th>CPF</th><th>CEP</th><th>DATA</th><th>TOTAL</th><th>STATUS</th></tr></thead><tbody>${list.map(o=>{const address=o.customer_address||{};return `<tr><td>${esc(o.order_nsu||"—")}</td><td>${esc(o.customer_name||"—")}</td><td>${esc(o.customer_cpf||"—")}</td><td>${esc(address.cep||"—")}</td><td>${date(o.created_at)}</td><td>${money(o.total)}</td><td><span class="badge ${esc(o.status||"pending")}">${esc(o.status||"pending")}</span></td></tr>`}).join("")}</tbody></table>`}
function renderOrders(){$("ordersTable").innerHTML=orderTable(orders)}
function openProduct(id=null){editingProduct=id?products.find(p=>p.id===id):null;$("modalTitle").textContent=editingProduct?"Editar produto":"Novo produto";$("productId").value=editingProduct?.id||"";$("productName").value=editingProduct?.name||"";$("productSku").value=editingProduct?.sku||"";$("productCategory").value=editingProduct?.category||"bolsas";$("productPrice").value=editingProduct?.price??"";$("productSalePrice").value=editingProduct?.sale_price??"";$("productImage").value=editingProduct?.images?.[0]||"";$("productDescription").value=editingProduct?.description||"";$("productNew").checked=!!editingProduct?.is_new;$("productSale").checked=!!editingProduct?.is_sale;$("productActive").checked=editingProduct?!!editingProduct.active:true;$("formError").textContent="";$("variantsList").innerHTML="";(editingProduct?.product_variants||[]).forEach(v=>addVariant(v));$("productModal").classList.remove("hidden")}
function closeProduct(){$("productModal").classList.add("hidden");editingProduct=null}
function addVariant(v={}){const row=document.createElement("div");row.className="variant-row";row.dataset.id=v.id||"";row.innerHTML=`<input class="v-color" placeholder="Cor" value="${esc(v.color||"")}"><input class="v-sku" placeholder="SKU da cor" value="${esc(v.sku||"")}"><input class="v-stock" type="number" min="0" value="${Number(v.stock||0)}"><button type="button" class="remove-variant">×</button>`;row.querySelector(".remove-variant").onclick=()=>row.remove();$("variantsList").appendChild(row)}
async function saveProduct(e){e.preventDefault();$("formError").textContent="";const id=$("productId").value;const payload={name:$("productName").value.trim(),sku:$("productSku").value.trim()||null,category:$("productCategory").value,price:Number($("productPrice").value),sale_price:$("productSalePrice").value?Number($("productSalePrice").value):null,description:$("productDescription").value.trim(),images:$("productImage").value.trim()?[$("productImage").value.trim()]:[],is_new:$("productNew").checked,is_sale:$("productSale").checked,active:$("productActive").checked};if(!payload.name){$("formError").textContent="Informe o nome.";return}try{const d=await api(id?`/api/admin/products/${encodeURIComponent(id)}`:"/api/admin/products",{method:id?"PUT":"POST",body:JSON.stringify(payload)});const pid=d.product.id;const variants=[...document.querySelectorAll(".variant-row")].map(r=>({id:r.dataset.id||null,color:r.querySelector(".v-color").value.trim(),sku:r.querySelector(".v-sku").value.trim()||null,stock:Math.max(0,Number(r.querySelector(".v-stock").value||0)),active:true})).filter(v=>v.color);await api(`/api/admin/products/${encodeURIComponent(pid)}/variants`,{method:"PUT",body:JSON.stringify({variants})});closeProduct();await loadProducts()}catch(e){$("formError").textContent=e.message}}
async function toggleProduct(id,active){const p=products.find(x=>x.id===id);if(!p)return;try{await api(`/api/admin/products/${encodeURIComponent(id)}`,{method:"PUT",body:JSON.stringify({name:p.name,sku:p.sku,category:p.category,price:p.price,sale_price:p.sale_price,description:p.description,images:p.images,is_new:p.is_new,is_sale:p.is_sale,active})});await loadProducts()}catch(e){alert(e.message)}}
function money(v){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0))}
function date(v){return v?new Date(v).toLocaleString("pt-BR"):"—"}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
